name: run-plato-analysis
run-name: ${{ github.actor }} is running Plato
on: 
  pull_request:
    branches: main
  push:
jobs:
  get_dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install -g plato
      - run: npm install json-easy-strip
  run_plato:
    needs: get_dependencies
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: node run_plato.js
